comments:
  CommentOverPrivateProperty:
    active: true
  EndOfSentenceFormat:
    active: true
  OutdatedDocumentation:
    active: true

style:
  MagicNumber:
    active: false
  ReturnCount:
    excludeGuardClauses: true